### ISSUE TITLE
Broken nested module functionality

### ISSUE THREAD

**Issue by aggarwaldev** [Rush/link-module-alias#12]
Hey,

Latest version of the package introduce nested module functionality.

But the same won't work in following cases:
```
"~project/root": ".",
"~project/app": "./app/",
"~project/dir": "./deep/nested/directory/",
```
Although this works just fine:
`"~project/config": "./config/index.js",`

It's pretty clear that module is not working correctly for nested directories. Can we fix this?

Here's the problem
https://github.com/Rush/link-module-alias/blob/d3a5fc9012bad017d45f008c95e000b920163d46/index.js#L178-L179

**Comment by aggarwaldev** [comment]
Ping: @Rush

**Comment by Rush** [comment]
Thanks for reporting @aggarwaldev 

@kwburnett - any ideas?

**Comment by kwburnett** [comment]
@aggarwaldev if you change your config to the following, it should work:
```"~project/root": ".",
"~project/app": "./app",
"~project/dir": "./deep/nested/directory",
```

Just so I can understand your use case, is there any reason why you don't do the above and have added a final slash? Is it just to denote to yourself it is a directory or is there also another reason?

**Comment by aggarwaldev** [comment]
@kwburnett Apologies for late reply. Never got a notification from github.

It's just to denote that it's a directory. Since the source files are being shared among other developers as well.
