### ISSUE TITLE
Not running postinstall in CircleCI

### ISSUE THREAD

**Issue by chemalopezp** [Rush/link-module-alias#18]
Hi @Rush , and thank you for this powerful module.
I found an issue when running it through CircleCI with 

```JSON
"scripts": {
  "postinstall": "link-module-alias"
},
"_moduleAliases": {
    "#lib": "lib"
  },
```

During the `npm ci` step I get the error:
```
~postinstall: cannot run in wd repo@1.0.0 link-module-alias (wd=/root/repo)
```

Any idea of why is failing and how I can solve it?

Thanks in advance

**Comment by Rush** [comment]
Sorry - no idea. Can you try running it manually as a separate step? Maybe it would show some additional errors.

**Comment by chemalopezp** [comment]
Thanks @Rush , in case it helps somebody else, CircleCI was having trouble to execute the postinstall script (due to additional permissions needed by the script... I guess). Changing to an official `circleci/node` image solved the issue.
