### ISSUE TITLE
Support junctions under Windows

### ISSUE THREAD

**Issue by k7sleeper** [Rush/link-module-alias#4]
I'm working under Windows, and for successfully use this fine module I have to work in an elevated command prompt.

That's undesirably!

Could you please support symbolic link type `'junction'` instead of `'dir'` under Windows. That would solve this unwanted behavior.

Mainly, you have to insert the following line

`const DIR_LINK_TYPE = ((process.platform === 'win32') ? 'junction' : 'dir');`

and use it

`await symlink(path.join('../', target), moduleDir, DIR_LINK_TYPE);`

Thanks!

**Comment by Rush** [comment]
@k7sleeper seems like you know perfectly what needs to be done - do you feel up for submitting a Pull Request? :-)

**Comment by k7sleeper** [comment]
sure

**Comment by Rush** [comment]
Fixed by #6 - sorry for taking the time to merge. I missed the notifications.
